### PR TITLE
fix: fix issue with usage of new version of scssphp

### PR DESCRIPTION
**Pull request by adam-buckley**
## Checklist
- [x] I'm using the correct PHP Version (8.1 for current, 7.4 for legacy).

## Description
Corrects usage of new version of the scssphp SCSS compiler
Formatted some files which is why the change set looks weird

### CODE REVIEW

**Comment by DerekCrannaford** [comment]
Adam - a couple of PlayWrite commits have lumped in on this.

 - added example test
 - fix: corrected helper reference

Was that intentional?

**Comment by adam-buckley** [comment]
@DerekCrannaford has this ended up in develop? Or does a review still need to be done?

**Comment by DerekCrannaford** [comment]
> @DerekCrannaford has this ended up in develop? Or does a review still need to be done?
It still shows diff against develop, so I presume it did not find another sneaky way in:
image


Looks fine to me, mostly formatting changes, with 'fix'  intention shown by ->GetCSS() method change?
It might need dev merged back to itself before proceeding?

**Review by DerekCrannaford — COMMENTED** [review]
Intended changes look OK.
Needs check of latest dev->into->fix before this PR gets merged?

**Review by DerekCrannaford — APPROVED** [review]

**Pull request merged**
