### PR TITLE
Hotfix: Fix running report permissions

### PR DESCRIPTION
**Pull request by Dark-Reef**
- Checks if users are members of reports before allowing the ability to view & run them

### CODE REVIEW

**Review by adam-buckley — CHANGES_REQUESTED** [review]
Not sure why addmembers has changed but I'm unsure if array_diff is the correct function to use, if you could add comments to this describing what is happening and why that should help me out a bit :)

**Comment by adam-buckley** [comment]
Also please remove all instances of the long "array" syntax and replace all magic service properties with the new getInstance function

**Comment by Dark-Reef** [comment]
> Not sure why addmembers has changed but I'm unsure if array_diff is the correct function to use, if you could add comments to this describing what is happening and why that should help me out a bit :)

Sorry, forgot to include this in the description. This is a bug I fixed while I already editing the report module fixes - the issue was that users could double up in the dropdown due to bugs in how the selection array was generated. It "says", it strips duplicates but it legit doesn't which is ironic. That whole segment of code is refactoring it so that it ACTUALLY strips duplicates

**Comment by adam-buckley** [comment]
[array_diff](https://www.php.net/manual/en/function.array-diff.php) returns the values in array1 that are *not* present in any of the other arrays. So what you should be left with are users in the ```$possibleMembers``` that are not in ```$currentMembers```. I think the function you're after is array_unique + array_merge?

**Comment by Dark-Reef** [comment]
> [array_diff](https://www.php.net/manual/en/function.array-diff.php) returns the values in array1 that are _not_ present in any of the other arrays. So what you should be left with are users in the `$possibleMembers` that are not in `$currentMembers`. I think the function you're after is array_unique + array_merge?

"Should be left with are users in the possiblesMembers that are not in $currentMembers" - Isn't this the intended behavior? We don't want the option to add currentMembers & since current members are also possible members, they need to be removed from the array. Array_unique & Array_merge WOULD also work though, so is it worth changing? Both ways should give the same result.

**Pull request merged**
