### PR TITLE
fix: check for arrays and objects

### PR DESCRIPTION
**Pull request by Tinystep1**
## Checklist
- [X] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
- [X] I've added comments to any new methods I've created or where else relevant.
- [X] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [X] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

Fixing depreciated warnings due to the use of array_key_exists being depreciated on objects

- added is_array($fields) && to options being set in the __construct function in Select.php

refs:
issues:

## Other Information

Docs pull request:

### CODE REVIEW

**Review by strongishllama — CHANGES_REQUESTED** [review]
@Tinystep1 I believe the original error was because the ```$fields``` parameter was an object instead of an array. If that's the case, you'll also want an ```else``` statement for each ```if``` statement that will treat ```$fields``` as an object and use the arrow operator (```->```) instead of the array operator (```[ ]```).

This would look something like.
```php
if (is_array($fields) && array_key_exists('options', $fields)) {
    $this->setOptions($fields['options']);
    $this->setOptions($fields['options']);
    unset($fields['options']);
    unset($fields['options']);
} else {
    $this->setOptions($fields->options);
    $this->setOptions($fields->options);
    $fields->options = null;
}
```

**Comment by Tinystep1** [comment]
> @Tinystep1 I believe the original error was because the `$fields` parameter was an object instead of an array. If that's the case, you'll also want an `else` statement for each `if` statement that will treat `$fields` as an object and use the arrow operator (`->`) instead of the array operator (`[ ]`).
> 
> This would look something like.
> 
> ```
> if (is_array($fields) && array_key_exists('options', $fields)) {
>     $this->setOptions($fields['options']);
>     $this->setOptions($fields['options']);
>     unset($fields['options']);
>     unset($fields['options']);
> } else {
>     $this->setOptions($fields->options);
>     $this->setOptions($fields->options);
>     $fields->options = null;
> }
> ```

$fields is not always an object. In the __construct function, it says $fields is an array. This stops an error from occurring if it is used with objects instead of an array. Will this fix cause any errors if $fields is an array?

**Comment by strongishllama** [comment]
> > @Tinystep1 I believe the original error was because the `$fields` parameter was an object instead of an array. If that's the case, you'll also want an `else` statement for each `if` statement that will treat `$fields` as an object and use the arrow operator (`->`) instead of the array operator (`[ ]`).
> > This would look something like.
> > ```
> > if (is_array($fields) && array_key_exists('options', $fields)) {
> >     $this->setOptions($fields['options']);
> >     $this->setOptions($fields['options']);
> >     unset($fields['options']);
> >     unset($fields['options']);
> > } else {
> >     $this->setOptions($fields->options);
> >     $this->setOptions($fields->options);
> >     $fields->options = null;
> > }
> > ```
> 
> $fields is not always an object. In the __construct function, it says $fields is an array. This stops an error from occurring if it is used with objects instead of an array. Will this fix cause any errors if $fields is an array?

@Tinystep1 The above snippet will handle both objects and arrays. You'll have to copy it for the second if statement on line 48 though. Also, I noticed that you merged the develop branch into this one. That means this branch will now have to be merged back into develop and not master.

**Comment by strongishllama** [comment]
@Tinystep1 Just noticed an issue with the example I gave you. I accidentally duplicated a few of those lines, it should be.
```php
if (is_array($fields) && array_key_exists('options', $fields)) {
    $this->setOptions($fields['options']);
    unset($fields['options']);
} else {
    $this->setOptions($fields->options);
    $fields->options = null;
}
```

**Comment by strongishllama** [comment]
@Tinystep1 you'll also need to change the branch into master. You can do it by clicking the edit button at the top right.

**Comment by Tinystep1** [comment]
> @Tinystep1 you'll also need to change the branch into master. You can do it by clicking the edit button at the top right.

What do you mean by changing the branch into master?

**Comment by strongishllama** [comment]
> > @Tinystep1 you'll also need to change the branch into master. You can do it by clicking the edit button at the top right.
> 
> What do you mean by changing the branch into master?

Into develop, sorry. Because you merged develop into your hotfix branch it needs to go back into develop now, not master.

**Comment by strongishllama** [comment]
@Tinystep1 looks like the tests are failing on this pull request.

**Review by strongishllama — APPROVED** [review]

**Comment by strongishllama** [comment]
@Tinystep1 Look good, just approved! Remember to **Squash and Merge**, not just **Merge** when you close this PR off!

**Pull request merged**
