### PR TITLE
feat: Insights JavaScript Fix

### PR DESCRIPTION
**Pull request by Tinystep1**
## Checklist
- [X] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
- [X] I've added comments to any new methods I've created or where else relevant.
- [X] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [X] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

Fixing issue with export to PDF option for insights

- Changed Vanilla JavaScript to jQuery where foundation function is used
- Removed duplicate of select option in drop-down for template select

refs: 10151

## Other Information

Docs pull request:

### CODE REVIEW

**Comment by strongishllama** [comment]
@Tinystep1 Maybe double check with @adam-buckley but I believe the plan is to remove jQuery from Cmfive.

**Comment by Tinystep1** [comment]
I changed it back after talking to Adam. The issue is Vanilla JavaScript
doesn't support the foundation function, which is required in order for the
export to PDF to work.

**Comment by DerekCrannaford** [comment]
> ## Checklist
> * [x]  I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
> * [x]  I've added comments to any new methods I've created or where else relevant.
> * [x]  I've replaced magic method usage on DbService classes with the getInstance() static method.
> * [x]  I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).
> 
> Fixing issue with export to PDF option for insights
> 
> * Changed Vanilla JavaScript to jQuery where foundation function is used
> * Removed duplicate of select option in drop-down for template select
> 
> refs: 10151
> 
> ## Other Information
> Docs pull request:

This PR contains problem code outside scope of commited/review changes:
 - in "system\modules\insights\models\InsightService.php"
 - lines 253->258 need to be _outside_ of iterator or else HTML/PDF concatenates recursively through multiple table interfaces
 - line 251 should read "headers" => $hds" (not "$hd") so that headers are correctly loaded

I can check these changes onto branch & assert a new PR, to prevent a merge-then-hotfix requirement on dev?

**Comment by Tinystep1** [comment]
This would be helpful. thanks

**Pull request merged**
