### PR TITLE
Bootstrap migrations

### PR DESCRIPTION
**Pull request by MaddyUnderStars**
This ones quite big and touches a lot of systems, so a thorough review is required.

*none* of the tests have been migrated yet.

general goals:
- migrate pages to bootstrap5 theme.
- - this theme does not include jquery, so it also requires rewriting a lot of systems to use plain js
- while I was writing something due to prev point, I might as well fix some bugs or improve small things
- lastly, if a page was written in plain html, it was easier to just make use of the form generation code or such in php since that already has all the bootstrap5 classes.

modules migrated:
- tag
- task
- timelog
- favourites

by page:
- /task/index ( dashboard )
- /task-group/viewtaskgrouptypes ( manage task groups )
- - uses quill editor instance of a plain text area
- /task/taskweek ( activity )
- /task/tasklist ( task list )
- /task/edit ( task view/edit )
- - only the edit/view and timelog tabs have been migrated currently, as the others are partials
- /task-group/viewmembergroup ( task group members/details page )
- /task-group/viewtaskgroup modal ('edit task group' button in viewmembergroup )
- /task/partials/listtasks
- /task/subscriber
- /task/subscriber/add
- /timelog/partial/listtimelog
- /timelog/index
- /timelog/edit
- /timelog/move
- /task-group/movetaskgroup modal
- /task-group/addgroupmembers

jquery:
- new php class Html5Autocomplete for multiselect free-form text input with autocomplete drop downs included with tom select
- removed jquery usage for CKEDITOR from html::form
- rewrite tags module client js to remove jquery dep.
- - tags module is now included in /system/templates/base/ so as to only include a single tags manager per page vs per inclusion of the partial
- - tags module now fetches tags via ajax
- - can now remove or add multiple tags at once via the modal (#250)
- Favourites
- - FavouriteService::getFavouriteButton now deprecated in favour of getBootstrapButton
- - Migrated favourites list modal to bootstrap

### CODE REVIEW

**Comment by MaddyUnderStars** [comment]
# Screenshots and video

<details>
	<summary>/task/index</summary>
	
</details>

<details>
	<summary>task-group/viewtaskgrouptypes</summary>
	
	
</details>

<details>
	<summary>/task/taskweek</summary>
	
</details>

<details>
	<summary>/task/tasklist</summary>
	
</details>

<details>
	<summary>/task/edit</summary>
	
	
	
	<video src="https://github.com/user-attachments/assets/f58a92f7-646c-4db4-ab7a-dfd1d854abf8"/>
</details>

<details>
	<summary>/task-group/viewmembergroup and /task/listtasks partial</summary>
	
	
</details>

<details>
	<summary>/task-group/viewtaskgroup modal</summary>
	
</details>

<details>
	<summary>/task/subscriber</summary>
	
	
</details>

<details>
	<summary>/task/listtimelog</summary>
	
	
</details>

<details>
	<summary>/timelog/index</summary>
	
</details>

<details>
	<summary>/timelog/edit</summary>
	
</details>

<details>
	<summary>/timelog/move</summary>
	
</details>

<details>
	<summary>/task-group/movetaskgroup modal</summary>
	
	
</details>

<details>
	<summary>/task-group/addgroupmembers modal</summary>
	
</details>

<details>
	<summary>add tags modal</summary>
	<video src="https://github.com/user-attachments/assets/30741181-8c68-405a-9ec7-d7b89dbc6346"/>
</details>

<details>
	<summary>favourites modal</summary>
	
</details>

**Comment by MaddyUnderStars** [comment]
I'm fixing some tests now. As of this comment, for the tag module tests to pass, you need this change: 2pisoftware/cmfive-boilerplate/pull/187

**Comment by iceaxeliehne** [comment]
edit taskgroup throws error when default assignee is set to 'unassigned'

**Comment by MaddyUnderStars** [comment]
Closed in favour of #389

**Pull request closed without merging**
